package com.fiap.foodcore.infrastructure.presenter;

import com.fiap.foodcore.application.usecase.input.CreateItemInput;
import com.fiap.foodcore.application.usecase.input.UpdateItemInput;
import com.fiap.foodcore.application.usecase.output.ItemCreateOutput;
import com.fiap.foodcore.infrastructure.web.controller.dto.item.ItemCreateRequestDTO;
import com.fiap.foodcore.infrastructure.web.controller.dto.item.ItemCreateResponseDTO;
import com.fiap.foodcore.infrastructure.web.controller.dto.item.ItemUpdateRequestDTO;

import java.util.List;

public class ItemPresenter {

    public static List<ItemCreateResponseDTO> toDtoList(List<ItemCreateOutput> outputs) {
        return outputs.stream()
                .map(output -> new ItemCreateResponseDTO(
                        output.id(),
                        output.name(),
                        output.description(),
                        output.price(),
                        output.availability(),
                        output.photo(),
                        output.ownerId()
                ))
                .toList();
    }

    public static ItemCreateOutput toOutput(ItemCreateRequestDTO dto) {
        return new ItemCreateOutput(
                null, // ID will be generated by the system
                dto.name(),
                dto.description(),
                dto.price(),
                dto.availability(),
                dto.photo(),
                dto.ownerId()
        );
    }

    public static ItemCreateResponseDTO toDto(ItemCreateOutput output) {
        return new ItemCreateResponseDTO(
                output.id(),
                output.name(),
                output.description(),
                output.price(),
                output.availability(),
                output.photo(),
                output.ownerId()
        );
    }

    public static CreateItemInput toInput(ItemCreateRequestDTO dto) {
        return new CreateItemInput(
                null,// ID will be generated by the system
                dto.name(),
                dto.description(),
                dto.price(),
                dto.availability(),
                dto.photo(),
                dto.ownerId()
        );
    }

    public static CreateItemInput toInput(ItemCreateRequestDTO dto, Long ownerId) {
        return new CreateItemInput(
                null, // ID will be generated by the system
                dto.name(),
                dto.description(),
                dto.price(),
                dto.availability(),
                dto.photo(),
                ownerId // Usando o ID do usuário autenticado em vez do que vem do DTO
        );
    }


    public static UpdateItemInput toUpdateInput(ItemUpdateRequestDTO dto) {
        return new UpdateItemInput(
                dto.id(),
                dto.name(),
                dto.description(),
                dto.price(),
                dto.availability(),
                dto.photo(),
                dto.ownerId()
        );
    }

}
