version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: container_postgres_foodcore
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: foodcore
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 3
    networks:
      - app-network

  app-foodcore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-foodcore
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network: