version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: container_mysql_auth
    environment:
      MYSQL_DATABASE: g10_auth
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app-g10-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-g10-auth
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network: